name: Build & Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build package
        run: yarn build

      - name: Automated tests
        run: yarn test

      - name: Debug Environment Variables
        run: |
          if [ -z "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" ]; then
            echo "CHROMATIC_PROJECT_TOKEN is not set or empty. ${{ secrets.CHROMATIC_PROJECT_TOKEN }}"
            exit 1
          else
            echo "CHROMATIC_PROJECT_TOKEN is set."
          fi
        shell: bash

      - name: Visual Regression Tests
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn test:chromatic
